name: i2c-directory-test

x-app: &app
  build:
    context: .
    target: development
  image: i2c-directory-dev:latest
  environment: &app_env
    DATABASE_HOST: postgresql
    DATABASE_USERNAME: postgres
    REDIS_URL: redis://redis:6379/0
    RAILS_ENV: test
  volumes:
    - .:/rails
    - node_modules:/rails/node_modules
    - bundle:/usr/local/bundle
  networks:
    - i2c-directory-test
  depends_on:
    postgresql:
      condition: service_healthy
    redis:
      condition: service_started

services:
  postgresql:
    container_name: i2c-directory-test-postgresql
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - i2c-directory-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    container_name: i2c-directory-test-redis
    image: redis:8
    networks:
      - i2c-directory-test

  sidekiq:
    <<: *app
    container_name: i2c-directory-test-sidekiq
    command: bundle exec sidekiq
    profiles:
      - sidekiq

  test:
    <<: *app
    command: bash -c "yarn build:css && bin/rails db:prepare && bin/rails test"

networks:
  i2c-directory-test:
    name: i2c-directory-test

volumes:
  node_modules:
  bundle:
